language: php

php:
  - 5.3
  - 5.4

env:
  - MONGO_VERSION=1.2.12
  - MONGO_VERSION=1.3.6

services: mongodb

before_script:
  - pecl install mongo-${MONGO_VERSION}
  - phpenv rehash
  - composer --dev install

script: phpunit